name: 'Python Safety Check'
#description: 'Helps to find known security vulnerabilities in your python application'
#author: aufdenpunkt

#inputs:
#  safety_args:
#    description: Optional Safety script parameters. (e.g. --ignore=1234 or -i 1234)
#    default: ''
#  scan_requirements_file_only:
#    description: Set true to scan required python packages without installing them.
#    default: 'false'
#branding:
#  icon: 'shield'
#  color: 'green'

on:
#on: [push]  
  push:
    branches:
      - main


env:
  DEP_PATH: requirements.txt
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out master
        uses: actions/checkout@master

      - name: Security vulnerabilities scan
        uses: aufdenpunkt/python-safety-check@master